language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t daopz23/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true daopz23/react-test npm test  

after_success:

  - docker build -t daopz23/multi-client ./client 
  - docker build -t daopz23/multi-nginx ./nginx
  - docker build -t daopz23/multi-server ./server
  - docker build -t daopz23/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push daopz23/multi-client
  - docker push daopz23/multi-nginx
  - docker push daopz23/multi-server
  - docker push daopz23/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-2-507856266964
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 

